INSERT INTO ${spark.var.catalog.dws}.ddm.dws_pfm_total
(
    data_source,                  -- 01. 数据来源渠道标识(如: tmall, jd)
    date_id,                      -- 02. 业务日期
    channel,                      -- 03. 原表一级触点/数据来源渠道
    mapping_channel,              -- 04. Mapping表触点|二级触点(京东特有)
    platform_id,                  -- 05. 平台ID/渠道平台id
    platform_name,                -- 06. 平台名称
    ea_id,                        -- 07. 企业账户ID
    ea_name,                      -- 08. 企业账户名称
    shop_id,                      -- 09. 店铺ID
    shop_name,                    -- 10. 店铺名称
    account_id,                   -- 11. 账户id(京东)
    account_name,                 -- 12. 账户名称(京东)
    oss_key,                      -- 13. 投放账户id(京东)
    pin_code,                     -- 14. 授权pin(京东)
    channel_id,                   -- 15. 一级渠道ID
    channel_name,                 -- 16. 一级渠道名称
    plan_id,                      -- 17. 计划ID
    plan_name,                    -- 18. 计划名称
    creative_id,                  -- 19. 创意ID
    creative_name,                -- 20. 创意名称
    creative_title,               -- 21. 创意标题(京东)
    material_id,                  -- 22. 素材id(京东)
    material_name,                -- 23. 素材名称(京东)
    creative_size,                -- 24. 创意尺寸(京东)
    creative_width,               -- 25. 创意宽度(京东)
    creative_height,              -- 26. 创意高度(京东)
    img_url,                      -- 27. 图片url
    img_flag,                     -- 28. 图片标识
    video_url,                    -- 29. 视频url
    land_page_url,                -- 30. 落地页地址
    material_creative_type,       -- 31. 素材创意类型
    ad_creative_type,             -- 32. ad创意类型
    main_id,                      --主体ID|词包ID(天猫)',
    main_name,                    --主体名称|词包名称(天猫)',
    bu,                           -- 33. BU
    category,                     -- 34. 品类
    old_category,                 -- 35. 旧品类(京东)
    brand,                        -- 36. 品牌
    product_line,                 -- 37. 产品线/系列
    sku_id,                       -- 38. SKU ID
    old_sku_id,                   -- 39. 旧商品id(京东)
    sku_name,                     -- 40. SKU名称(京东sku_name对齐天猫sku)
    sku_type,                     -- 41. sku类型(京东)
    is_npd,                       -- 42. 是否新品
    itm_dim,                      -- 43. 商品维度(京东)
    dir_type,                     -- 44. 定向方式(京东)
    promote_device,               -- 45. 推广设备类型(京东)
    fee_type,                     -- 46. 费用类型(京东)
    trans_cycle,                  -- 47. 转化周期
    crt_or_pay,                   -- 48. 下单订单/成交订单(京东)
    in_no_zp,                     -- 49. 含赠品/不含赠品(京东)
    day_report,                   -- 50. 分日报告(京东)
    clk_or_crt,                   -- 51. 点击/下单口径(京东)
    push_type,                    -- 52. 投放类型(京东)
    impression_cnt,               -- 53. 展现量(京东impress_cnt合入)
    click_cnt,                    -- 54. 点击量(京东clk_cnt合入)
    click_rate,                   -- 55. 点击率(京东clk_rate合入)
    vst_pv,                       -- 56. 观看次数/访问页面数(京东stay_page_cnt合入)
    vst_uv,                       -- 57. 访客数(京东ad2vst_cnt合入)
    avg_vst_interval,             -- 58. 平均观看时长(京东avg_stay_time_len合入)
    deepth_enterslr_cnt,          -- 59. 深度进店数(京东)
    reserve_cnt,                  -- 60. 预约数(京东)
    get_ticket_cnt,               -- 61. 领券数(京东)
    video_views,                  -- 62. 视频播放次数(京东)
    valid_video_views,            -- 63. 视频有效播放量(京东)
    valid_view_rate,              -- 64. 视频有效播放率(京东)
    play_25per_vv,                -- 65. 25%进度播放数(京东)
    play_50per_vv,                -- 66. 50%进度播放数(京东)
    play_75per_vv,                -- 67. 75%进度播放数(京东)
    play_100per_vv,               -- 68. 100%进度播放数(京东)
    views_10pct,                  -- 69. 10%进度播放数(京东)
    views_95pct,                  -- 70. 95%进度播放数(京东)
    views_3s_complete,            -- 71. 3s播放完成量(京东)
    views_5s_complete,            -- 72. 5s播放完成量(京东)
    views_7s_complete,            -- 73. 7s播放完成量(京东)
    completion_rate,              -- 74. 视频播完率(京东)
    disinterest_clicks,           -- 75. 不感兴趣点击次数(京东)
    all_cart_itm_cnt,             -- 76. 总加购数(京东all_cart_cnt合入)
    dir_cart_itm_cnt,             -- 77. 直接加购数(京东dir_cart_cnt合入)
    indir_cart_itm_cnt,           -- 78. 间接加购数(京东indir_cart_cnt合入)
    cart_rate,                    -- 79. 加购率
    clt_itm_cnt,                  -- 80. 宝贝收藏数(京东flw_itm_cnt合入)
    clt_slr_cnt,                  -- 81. 店铺收藏数(京东flw_slr_cnt合入)
    trans_rate,                   -- 82. 转化率
    all_pay_ord_cnt,              -- 83. 总支付订单/总订单行
    dir_pay_ord_cnt,              -- 84. 直接支付订单笔数/行
    indir_pay_ord_cnt,            -- 85. 间接支付订单笔数/行
    all_pre_ord_cnt,              -- 86. 总预售成交笔数(京东pre_pay_ord_cnt合入)
    all_pay_ord_amt,              -- 87. 总支付/下单金额
    dir_pay_ord_amt,              -- 88. 直接支付金额
    indir_pay_ord_amt,            -- 89. 间接支付金额
    all_pre_ord_amt,              -- 90. 总预售订单金额(京东pre_pay_ord_amt合入)
    pay_new_user_cnt,             -- 91. 新用户支付笔数(京东pay_newer_cnt合入)
    new_customers,                -- 92. 新客数(京东)
    new_orders,                   -- 93. 新客订单行(京东)
    new_order_value,              -- 94. 新客订单金额(京东)
    cost,                         -- 95. 花费/消耗
    roi,                          -- 96. 投入产出比
    impress_cpm,                  -- 97. 千次展现花费/成本
    avg_clk_cost,                 -- 98. 平均点击花费/成本
    valid_view_cost,              -- 99. 有效播放成本(京东)
    store_follow_cost,            -- 100. 店铺关注成本(京东)
    product_follow_cost,          -- 101. 商品关注成本(京东)
    cart_itm_cost,                -- 102. 加购商品成本
    cart_cost,                    -- 103. 加购成本(京东)
    all_pay_ord_cost,             -- 104. 总成交成本(京东cpa合入)
    new_customer_cost,            -- 105. 新客成本(京东)
    allsite_ord_amt,              -- 106. 全站交易额
    allsite_ord_cnt,              -- 107. 全站订单行
    allsite_ord_cost,             -- 108. 全站订单成本
    allsite_fee_ratio,            -- 109. 全站费比
    allsite_roi,                  -- 110. 全站投产比
    order_id,                     -- 111. 订单id
    order_name,                   -- 112. 订单名称
    schedule_id,                  -- 113. 排期id
    schedule_name,                -- 114. 排期名称
    ad_slot_id,                   -- 115. 广告位id
    ad_slot_name,                 -- 116. 广告位名称
    exp_pv,                       -- 117. 曝光数(合约)
    exp_clk_cnt,                  -- 118. 曝光点击数(合约)
    exp_clk_rate,                 -- 119. 曝光点击率(合约)
    start_time,                   -- 120. 开始时间
    expire_time,                  -- 121. 到期时间
    plan_type,                    -- 122. 计划类型
    market_scene,                 -- 123. 营销场景
    status,                       -- 124. 状态
    item_sku,                     -- 125. 商品sku(直播)
    resource_slot,                -- 126. 资源位
    media_type,                   -- 127. 媒体类型
    placement,                    -- 128. 投放位置
    one_click_cost,               -- 129. 一键起量花费
    clk_date,                     -- 130. 点击日期(京东)
    clk_time,                     -- 131. 点击时间(京东)
    uuid,                         -- 132. 唯一ID/行标识(京东ly_uuid对齐至此)
    file_id,                      -- 133. 来源文件ID/系统唯一标识
    file_name                     -- 134. 来源文件名
)
SELECT 
    'jd' AS data_source,          -- 01. 数据来源渠道标识(如: tmall, jd)
    date_id,                      -- 02. 业务日期
    channel,                      -- 03. 原表一级触点/数据来源渠道
    mapping_channel,              -- 04. Mapping表触点|二级触点(京东特有)
    platform_id,                  -- 05. 平台ID/渠道平台id
    platform_name,                -- 06. 平台名称
    ea_id,                        -- 07. 企业账户ID
    ea_name,                      -- 08. 企业账户名称
    shop_id,                      -- 09. 店铺ID
    shop_name,                    -- 10. 店铺名称
    account_id,                   -- 11. 账户id(京东)
    account_name,                 -- 12. 账户名称(京东)
    oss_key,                      -- 13. 投放账户id(京东)
    pin_code,                     -- 14. 授权pin(京东)
    channel_id,                   -- 15. 一级渠道ID
    channel_name,                 -- 16. 一级渠道名称
    plan_id,                      -- 17. 计划ID
    plan_name,                    -- 18. 计划名称
    creative_id,                  -- 19. 创意ID
    creative_name,                -- 20. 创意名称
    creative_title,               -- 21. 创意标题(京东)
    material_id,                  -- 22. 素材id(京东)
    material_name,                -- 23. 素材名称(京东)
    creative_size,                -- 24. 创意尺寸(京东)
    creative_width,               -- 25. 创意宽度(京东)
    creative_height,              -- 26. 创意高度(京东)
    img_url,                      -- 27. 图片url
    img_flag,                     -- 28. 图片标识
    video_url,                    -- 29. 视频url
    land_page_url,                -- 30. 落地页地址
    material_creative_type,       -- 31. 素材创意类型
    ad_creative_type,             -- 32. ad创意类型
    unit_id as main_id,           --主体ID|词包ID|单元id',
    unit_name as main_name,       --主体名称|词包名称'|单元id,
    bu,                           -- 33. BU
    category,                     -- 34. 品类
    old_category,                 -- 35. 旧品类(京东)
    brand,                        -- 36. 品牌
    product_line,                 -- 37. 产品线/系列
    sku_id,                       -- 38. SKU ID
    old_sku_id,                   -- 39. 旧商品id(京东)
    sku_name,                     -- 40. SKU名称(京东sku_name对齐天猫sku)
    sku_type,                     -- 41. sku类型(京东)
    is_npd,                       -- 42. 是否新品
    itm_dim,                      -- 43. 商品维度(京东)
    dir_type,                     -- 44. 定向方式(京东)
    promote_device,               -- 45. 推广设备类型(京东)
    fee_type,                     -- 46. 费用类型(京东)
    trans_cycle,                  -- 47. 转化周期
    crt_or_pay,                   -- 48. 下单订单/成交订单(京东)
    in_no_zp,                     -- 49. 含赠品/不含赠品(京东)
    day_report,                   -- 50. 分日报告(京东)
    clk_or_crt,                   -- 51. 点击/下单口径(京东)
    push_type,                    -- 52. 投放类型(京东)
    impress_cnt as impression_cnt,                  -- 53. 展现量(京东impress_cnt合入)
    clk_cnt as click_cnt,                      -- 54. 点击量(京东clk_cnt合入) 
    clk_rate as click_rate,                     -- 55. 点击率(京东clk_rate合入)
    stay_page_cnt,                -- 56. 观看次数/访问页面数(京东stay_page_cnt合入)
    ad2vst_cnt,                   -- 57. 访客数(京东ad2vst_cnt合入)
    avg_stay_time_len,            -- 58. 平均观看时长(京东avg_stay_time_len合入)
    deepth_enterslr_cnt,          -- 59. 深度进店数(京东)
    reserve_cnt,                  -- 60. 预约数(京东)
    get_ticket_cnt,               -- 61. 领券数(京东)
    video_views,                  -- 62. 视频播放次数(京东)
    valid_video_views,            -- 63. 视频有效播放量(京东)
    valid_view_rate,              -- 64. 视频有效播放率(京东)
    play_25per_vv,                -- 65. 25%进度播放数(京东)
    play_50per_vv,                -- 66. 50%进度播放数(京东)
    play_75per_vv,                -- 67. 75%进度播放数(京东)
    play_100per_vv,               -- 68. 100%进度播放数(京东)
    views_10pct,                  -- 69. 10%进度播放数(京东)
    views_95pct,                  -- 70. 95%进度播放数(京东)
    views_3s_complete,            -- 71. 3s播放完成量(京东)
    views_5s_complete,            -- 72. 5s播放完成量(京东)
    views_7s_complete,            -- 73. 7s播放完成量(京东)
    completion_rate,              -- 74. 视频播完率(京东)
    disinterest_clicks,           -- 75. 不感兴趣点击次数(京东)
    all_cart_cnt,                 -- 76. 总加购数(京东all_cart_cnt合入)
    dir_cart_cnt,                 -- 77. 直接加购数(京东dir_cart_cnt合入)
    indir_cart_cnt,               -- 78. 间接加购数(京东indir_cart_cnt合入)
    cart_rate,                    -- 79. 加购率
    flw_itm_cnt,                  -- 80. 宝贝收藏数(京东flw_itm_cnt合入)
    flw_slr_cnt,                  -- 81. 店铺收藏数(京东flw_slr_cnt合入)
    trans_rate,                   -- 82. 转化率
    all_pay_ord_cnt,              -- 83. 总支付订单/总订单行
    dir_pay_ord_cnt,              -- 84. 直接支付订单笔数/行
    indir_pay_ord_cnt,            -- 85. 间接支付订单笔数/行
    pre_pay_ord_cnt,              -- 86. 总预售成交笔数(京东pre_pay_ord_cnt合入)
    all_pay_ord_amt,              -- 87. 总支付/下单金额
    dir_pay_ord_amt,              -- 88. 直接支付金额
    indir_pay_ord_amt,            -- 89. 间接支付金额
    pre_pay_ord_amt,              -- 90. 总预售订单金额(京东pre_pay_ord_amt合入)
    pay_newer_cnt,                -- 91. 新用户支付笔数(京东pay_newer_cnt合入)
    new_customers,                -- 92. 新客数(京东)
    new_orders,                   -- 93. 新客订单行(京东)
    new_order_value,              -- 94. 新客订单金额(京东)
    cost,                         -- 95. 花费/消耗
    roi,                          -- 96. 投入产出比
    impress_cpm,                  -- 97. 千次展现花费/成本
    avg_clk_cost,                 -- 98. 平均点击花费/成本
    valid_view_cost,              -- 99. 有效播放成本(京东)
    store_follow_cost,            -- 100. 店铺关注成本(京东)
    product_follow_cost,          -- 101. 商品关注成本(京东)
    cart_itm_cost,                -- 102. 加购商品成本
    cart_cost,                    -- 103. 加购成本(京东)
    cpa,                          -- 104. 总成交成本(京东cpa合入)
    new_customer_cost,            -- 105. 新客成本(京东)
    allsite_ord_amt,              -- 106. 全站交易额
    allsite_ord_cnt,              -- 107. 全站订单行
    allsite_ord_cost,             -- 108. 全站订单成本
    allsite_fee_ratio,            -- 109. 全站费比
    allsite_roi,                  -- 110. 全站投产比
    order_id,                     -- 111. 订单id
    order_name,                   -- 112. 订单名称
    schedule_id,                  -- 113. 排期id
    schedule_name,                -- 114. 排期名称
    ad_slot_id,                   -- 115. 广告位id
    ad_slot_name,                 -- 116. 广告位名称
    exp_pv,                       -- 117. 曝光数(合约)
    exp_clk_cnt,                  -- 118. 曝光点击数(合约)
    exp_clk_rate,                 -- 119. 曝光点击率(合约)
    start_time,                   -- 120. 开始时间
    expire_time,                  -- 121. 到期时间
    plan_type,                    -- 122. 计划类型
    market_scene,                 -- 123. 营销场景
    status,                       -- 124. 状态
    item_sku,                     -- 125. 商品sku(直播)
    resource_slot,                -- 126. 资源位
    media_type,                   -- 127. 媒体类型
    placement,                    -- 128. 投放位置
    one_click_cost,               -- 129. 一键起量花费
    clk_date,                     -- 130. 点击日期(京东)
    clk_time,                     -- 131. 点击时间(京东)
    ly_uuid,                      -- 132. 唯一ID/行标识(京东ly_uuid对齐至此)
    file_id,                      -- 133. 来源文件ID/系统唯一标识
    file_name                     -- 134. 来源文件名
FROM ${spark.var.catalog.dwd}.ddm.dwd_jd_pfm_sku;
