DROP TABLE IF EXISTS ${spark.var.catalog.dws}.ddm.dws_pfm_total;

CREATE TABLE IF NOT EXISTS ${spark.var.catalog.dws}.ddm.dws_pfm_total
(
    -- =====================================================================
    -- 1. 系统溯源与底层标识域 (System & Lineage)
    -- =====================================================================
    data_source            STRING       COMMENT '数据来源渠道标识(如: tmall, jd)',
    source_id               STRING       COMMENT '数据源id(拼多多)',
    date_id                 STRING       COMMENT '业务日期',
    month                   STRING       COMMENT '月份(拼多多)',
    channel                 STRING       COMMENT '原表一级触点/数据来源渠道',
    mapping_channel         STRING       COMMENT 'Mapping表触点|二级触点(京东特有)',

    -- =====================================================================
    -- 2. 核心维度域：组织、架构与商品 (Dimensions)
    -- =====================================================================
    platform_id             STRING       COMMENT '平台ID/渠道平台id',
    platform_name           STRING       COMMENT '平台名称',
    ea_id                   STRING       COMMENT '企业账户ID',
    ea_name                 STRING       COMMENT '企业账户名称',
    shop_id                 STRING       COMMENT '店铺ID',
    shop_name               STRING       COMMENT '店铺名称',
    site_name               STRING       COMMENT '站点名称(拼多多)',
    account_id              STRING       COMMENT '账户id(京东)',
    account_name            STRING       COMMENT '账户名称(京东)',
    oss_key                 STRING       COMMENT '投放账户id(京东)',
    pin_code                STRING       COMMENT '授权pin(京东)',
    
    channel_id              STRING       COMMENT '一级渠道ID',
    channel_name            STRING       COMMENT '一级渠道名称',
    plan_id                 STRING       COMMENT '计划ID',
    plan_name               STRING       COMMENT '计划名称',
    plan_page_name          STRING       COMMENT '投放页面名称(拼多多)',
    scene_id                STRING       COMMENT '场景ID(天猫)',
    scene_name              STRING       COMMENT '场景名称(天猫)',
    scene_id_oldlv2         STRING       COMMENT '历史二级场景ID(天猫)',
    scene_name_oldlv2       STRING       COMMENT '历史二级场景名称(天猫)',
    dim_name                STRING       COMMENT '维度名称',
    group_name              STRING       COMMENT '分组(拼多多)',
    
    creative_id             STRING       COMMENT '创意ID',
    creative_name           STRING       COMMENT '创意名称',
    creative_title          STRING       COMMENT '创意标题(京东)',
    material_id             STRING       COMMENT '素材id(京东)',
    material_name           STRING       COMMENT '素材名称(京东)',
    creative_size           STRING       COMMENT '创意尺寸(京东)',
    creative_width          STRING       COMMENT '创意宽度(京东)',
    creative_height         STRING       COMMENT '创意高度(京东)',
    img_url                 STRING       COMMENT '图片url',
    img_flag                STRING       COMMENT '图片标识',
    video_url               STRING       COMMENT '视频url',
    land_page_url           STRING       COMMENT '落地页地址',
    material_creative_type  STRING       COMMENT '素材创意类型',
    ad_creative_type        STRING       COMMENT 'ad创意类型',
    
    main_id                 STRING       COMMENT '主体ID|词包ID(天猫)',
    main_name               STRING       COMMENT '主体名称|词包名称(天猫)',
    main_type               STRING       COMMENT '主体类型|商品类型(天猫)',
    bu                      STRING       COMMENT 'BU',    
    category                STRING       COMMENT '品类',
    old_category            STRING       COMMENT '旧品类(京东)',
    sub_category            STRING       COMMENT '子分类(拼多多)',
    tier                    STRING       COMMENT '层级(拼多多)',
    brand                   STRING       COMMENT '品牌',
    product_line            STRING       COMMENT '产品线/系列',
    sku_id                  STRING       COMMENT 'SKU ID',
    old_sku_id              STRING       COMMENT '旧商品id(京东)',
    sku_name                STRING       COMMENT 'SKU名称(京东sku_name对齐天猫sku)',
    sku_type                STRING       COMMENT 'sku类型(京东)',
    is_npd                  STRING       COMMENT '是否新品',
    itm_dim                 STRING       COMMENT '商品维度(京东)',
    
    crowd_name              STRING       COMMENT '人群名称(天猫)',
    attribution_model       STRING       COMMENT '归因模型(天猫)',
    unify_type              STRING       COMMENT '归因口径(天猫)',
    dir_type                STRING       COMMENT '定向方式(京东)',
    promote_device          STRING       COMMENT '推广设备类型(京东)',
    fee_type                STRING       COMMENT '费用类型(京东)',
    spending_type           STRING       COMMENT '支出类型(拼多多)',
    bidding_method          STRING       COMMENT '出价方式(拼多多)',
    trans_cycle             STRING       COMMENT '转化周期',
    crt_or_pay              STRING       COMMENT '下单订单/成交订单(京东)',
    in_no_zp                STRING       COMMENT '含赠品/不含赠品(京东)',
    day_report              STRING       COMMENT '分日报告(京东)',
    clk_or_crt              STRING       COMMENT '点击/下单口径(京东)',
    push_type               STRING       COMMENT '投放类型(京东)',
    is_delete               STRING       COMMENT '是否已删除(拼多多)',

    -- =====================================================================
    -- 3. 过程流量与互动指标 (Traffic & Interaction)
    -- =====================================================================
    impression_cnt          STRING       COMMENT '展现量(京东impress_cnt合入)',
    click_cnt               STRING       COMMENT '点击量(京东clk_cnt合入)',
    click_rate              STRING       COMMENT '点击率(京东clk_rate合入)',
    click_buy_rate          STRING       COMMENT '点击购买率(拼多多)',
    avg_display_rank        STRING       COMMENT '平均展现排名(天猫)',
    clk_uv                  STRING       COMMENT '点击访客数',
    touch_uv                STRING       COMMENT '触达访客数',

    vst_itm_cnt             STRING       COMMENT '宝贝浏览数 #67',
    vst_slr_cnt             STRING       COMMENT '店铺浏览数 #68',
    vst_itm_uv              STRING       COMMENT '宝贝浏览访客数 #69',
    vst_pv                  STRING       COMMENT '观看次数/访问页面数(京东stay_page_cnt合入)',
    vst_uv                  STRING       COMMENT '访客数(京东ad2vst_cnt合入)',
    vst_rate                STRING       COMMENT '观看率',
    avg_vst_interval        STRING       COMMENT '平均观看时长(京东avg_stay_time_len合入)',
    avg_vst_page_cnt        STRING       COMMENT '平均访问页面数',
    depth_vst_pv            STRING       COMMENT '深度访问量',
    deepth_enterslr_cnt     STRING       COMMENT '深度进店数(京东)',
    stay_time_len           STRING       COMMENT '访问时长总计(天猫)',
    valid_vst_pv            STRING       COMMENT '有效观看量',
    valid_vst_rate          STRING       COMMENT '有效观看率',
    avg_valid_vst_interval  STRING       COMMENT '平均有效观看时长',
    
    cmt_pv                  STRING       COMMENT '评论量',
    like_pv                 STRING       COMMENT '点赞量',
    share_pv                STRING       COMMENT '转发量',
    inav_pv                 STRING       COMMENT '互动量',
    inav_rate               STRING       COMMENT '互动率',
    clk_inav_pv             STRING       COMMENT '互动点击量',
    clk_jump_pv             STRING       COMMENT '跳转点击量',
    clk_jump_rate           STRING       COMMENT '跳转点击率',
    act_uv                  STRING       COMMENT '行动访客数',
    enterslr_pv             STRING       COMMENT '进店量',
    enterslr_rate           STRING       COMMENT '进店率',
    enterslr_uv             STRING       COMMENT '进店访客数',
    search_pv               STRING       COMMENT '搜索访客量',
    search_uv               STRING       COMMENT '搜索访客数',
    research_impress_cnt    STRING       COMMENT '回搜展现量',
    research_clk_pv         STRING       COMMENT '回搜点击量',
    research_clk_uv         STRING       COMMENT '回搜点击访客数',
    research_touch_uv       STRING       COMMENT '回搜触达访客数',
    clk_module_cnt          STRING       COMMENT '组件点击数',
    ww_cslt_vlm             STRING       COMMENT '旺旺咨询量',
    reserve_cnt             STRING       COMMENT '预约数(京东)',
    get_ticket_cnt          STRING       COMMENT '领券数(京东)',
    inquiry_count           STRING       COMMENT '询单量(拼多多)',
    
    live_pv                 STRING       COMMENT '直播观看量',
    live_like_pv            STRING       COMMENT '直播点赞量',
    live_share_pv           STRING       COMMENT '直播分享量',
    live_cmt_cnt            STRING       COMMENT '直播评论量',
    gd2live_total_vst_pv    STRING       COMMENT '引流直播间总观看次数',
    vdo2live_trans_ratio    STRING       COMMENT '视频引流直播观看占比',
    video_views             STRING       COMMENT '视频播放次数(京东)',
    valid_video_views       STRING       COMMENT '视频有效播放量(京东)',
    valid_view_rate         STRING       COMMENT '视频有效播放率(京东)',
    play_25per_vv           STRING       COMMENT '25%进度播放数(京东)',
    play_50per_vv           STRING       COMMENT '50%进度播放数(京东)',
    play_75per_vv           STRING       COMMENT '75%进度播放数(京东)',
    play_100per_vv          STRING       COMMENT '100%进度播放数(京东)',
    views_10pct             STRING       COMMENT '10%进度播放数(京东)',
    views_95pct             STRING       COMMENT '95%进度播放数(京东)',
    views_3s_complete       STRING       COMMENT '3s播放完成量(京东)',
    views_5s_complete       STRING       COMMENT '5s播放完成量(京东)',
    views_7s_complete       STRING       COMMENT '7s播放完成量(京东)',
    completion_rate         STRING       COMMENT '视频播完率(京东)',
    disinterest_clicks      STRING       COMMENT '不感兴趣点击次数(京东)',

    gd_vst_pv               STRING       COMMENT '引导平台访问pv',
    gd_vst_uv               STRING       COMMENT '引导平台访问uv',
    gd_vst_rate             STRING       COMMENT '引导平台访问率',
    gd_ptnler_vst_uv        STRING       COMMENT '平台访问潜客数',
    gd_ptnler_vst_rate      STRING       COMMENT '平台访问潜客占比',
    natural_flow_trans_exp  STRING       COMMENT '自然流量增量曝光',

    -- =====================================================================
    -- 4. 转化指标域：收藏/关注与加购 (Add to Cart & Favorite)
    -- =====================================================================
    all_cart_itm_cnt        STRING       COMMENT '总加购数(京东all_cart_cnt合入)',
    dir_cart_itm_cnt        STRING       COMMENT '直接加购数(京东dir_cart_cnt合入)',
    indir_cart_itm_cnt      STRING       COMMENT '间接加购数(京东indir_cart_cnt合入)',
    cart_itm_cnt            STRING       COMMENT '宝贝/商品加购数',
    cart_itm_uv             STRING       COMMENT '宝贝加购访客数',
    cart_rate               STRING       COMMENT '加购率',
    
    all_clt_itm_cnt         STRING       COMMENT '总收藏/关注数',
    dir_clt_itm_cnt         STRING       COMMENT '直接收藏宝贝数',
    indir_clt_itm_cnt       STRING       COMMENT '间接收藏宝贝数',
    clt_itm_cnt             STRING       COMMENT '宝贝收藏数(京东flw_itm_cnt合入)',
    clt_slr_cnt             STRING       COMMENT '店铺收藏数(京东flw_slr_cnt合入)',
    clt_itm_uv              STRING       COMMENT '宝贝收藏访客数',
    clt_slr_uv              STRING       COMMENT '店铺收藏访客数',
    flr_uv                  STRING       COMMENT '关注访客数(天猫)',
    flw_uv                  STRING       COMMENT '粉丝关注量(天猫)',
    clt_itm_rate            STRING       COMMENT '宝贝收藏率',
    
    all_clt_cart_itm_cnt    STRING       COMMENT '总收藏加购数',
    clt_cart_itm_cnt        STRING       COMMENT '宝贝收藏加购数',
    clt_cart_itm_rate       STRING       COMMENT '宝贝收藏加购率',

    -- =====================================================================
    -- 5. 结果指标域：订单与金额 (Orders & GMV)
    -- =====================================================================
    trans_rate              STRING       COMMENT '转化率',
    clk_trans_rate          STRING       COMMENT '点击转化率',
    pay_trans_rate          STRING       COMMENT '成交转化率',
    se2enterslr_trans_rate  STRING       COMMENT '搜索进店率',
    enterslr2act_trans_rate STRING       COMMENT '进店行动率',
    act2pay_trans_rate      STRING       COMMENT '行动成交率',
    trans_effect            STRING       COMMENT '转化效果',
    
    crt_ord_cnt             STRING       COMMENT '拍下订单笔数',
    all_pay_ord_cnt         STRING       COMMENT '总支付订单/总订单行',
    dir_pay_ord_cnt         STRING       COMMENT '直接支付订单笔数/行',
    indir_pay_ord_cnt       STRING       COMMENT '间接支付订单笔数/行',
    all_pre_ord_cnt         STRING       COMMENT '总预售成交笔数(京东pre_pay_ord_cnt合入)',
    dir_pre_ord_cnt         STRING       COMMENT '直接预售成交笔数',
    indir_pre_ord_cnt       STRING       COMMENT '间接预售成交笔数',
    
    ord_plc_amt             STRING       COMMENT '拍下订单金额',
    all_pay_ord_amt         STRING       COMMENT '总支付/下单金额',
    dir_pay_ord_amt         STRING       COMMENT '直接支付金额',
    indir_pay_ord_amt       STRING       COMMENT '间接支付金额',
    per_direct_transaction_amount   STRING       COMMENT '每笔直接成交金额(拼多多)',
    per_indirect_transaction_amount STRING       COMMENT '每笔间接成交金额(拼多多)',
    per_transaction_spending        STRING       COMMENT '每笔成交花费(拼多多)',
    per_transaction_amount          STRING       COMMENT '每笔成交金额(拼多多)',
    net_transaction_amount          STRING       COMMENT '净交易额(拼多多)',
    net_transaction_count           STRING       COMMENT '净成交笔数(拼多多)',
    per_net_transaction_spending    STRING       COMMENT '每笔净成交花费(拼多多)',
    net_transaction_ratio           STRING       COMMENT '净交易额占比(拼多多)',
    all_pre_ord_amt         STRING       COMMENT '总预售订单金额(京东pre_pay_ord_amt合入)',
    dir_pre_ord_amt         STRING       COMMENT '直接预售订单金额',
    indir_pre_ord_amt       STRING       COMMENT '间接预售订单金额',
    natural_flow_trans_pay  STRING       COMMENT '自然流量增量成交',
    
    avg_pay_ord_cnt         STRING       COMMENT '人均成交笔数',
    avg_pay_ord_amt         STRING       COMMENT '人均成交金额',
    pay_byr_cnt             STRING       COMMENT '成交人数/买家数',
    rc_gwj_cnt              STRING       COMMENT '购物金充值笔数',
    rc_gwj_amt              STRING       COMMENT '购物金充值金额',
    coupon_rdmpt_cnt        STRING       COMMENT '优惠券领取量',

    -- =====================================================================
    -- 6. 客户圈层域：新客与会员 (Newer & Member)
    -- =====================================================================
    pay_new_user_cnt        STRING       COMMENT '新用户支付笔数(京东pay_newer_cnt合入)',
    pay_new_user_rate       STRING       COMMENT '新用户支付转化率',
    new_customers           STRING       COMMENT '新客数(京东)',
    new_orders              STRING       COMMENT '新客订单行(京东)',
    new_order_value         STRING       COMMENT '新客订单金额(京东)',
    touch_newer_cnt         STRING       COMMENT '新客触达数',
    vst_newer_pv            STRING       COMMENT '新客观看次数',
    newer_cover_rate        STRING       COMMENT '新客覆盖率',
    newer_pay_trans_rate    STRING       COMMENT '新客成交转化率',
    enterslr_newer_uv       STRING       COMMENT '进店新客人数',
    inav_newer_uv           STRING       COMMENT '互动新客人数',
    ntl_trf_exp             STRING       COMMENT '新流量曝光',
    ntl_trf_cvr_amt         STRING       COMMENT '新流量转化金额',
    dir_pay_ord_amt_ratio   STRING       COMMENT '新客直接引导成交金额占比',
    dir_pre_ord_amt_ratio   STRING       COMMENT '新客直接引导预售成交金额占比',
    
    mbr_cnt                 STRING       COMMENT '会员数',
    mbr_rate                STRING       COMMENT '会员转化率',
    mbr_uv                  STRING       COMMENT '入会量',
    mbr_first_purchase_cnt  STRING       COMMENT '会员首购人数',
    mbr_pay_ord_cnt         STRING       COMMENT '会员成交笔数',
    mbr_pay_ord_amt         STRING       COMMENT '会员成交金额',
    
    zc_crowd_retarget_gd_pay_amt STRING       COMMENT '种草人群追投引导成交金额',

    -- =====================================================================
    -- 7. 财务考核域：消耗、成本与ROI (Cost & ROI)
    -- =====================================================================
    cost                    STRING       COMMENT '花费/消耗',
    roi                     STRING       COMMENT '投入产出比',
    net_actual_roi          STRING       COMMENT '净实际投产比(拼多多)',
    total_site_promotion_ratio STRING    COMMENT '全站推广费比(拼多多)',
    dir_pay_ord_roi         STRING       COMMENT '直接支付roi',
    newer_roi               STRING       COMMENT '新客投入产出比',
    return_rate             STRING       COMMENT '回报率',
    zc_pay_roi              STRING       COMMENT '种草引导成交ROI',
    zc_crowd_retarget_roi   STRING       COMMENT '种草人群追投roi',
    
    impress_cpm             STRING       COMMENT '千次展现花费/成本',
    cost_per_tosd_impres    STRING       COMMENT '每次展示成本',
    avg_clk_cost            STRING       COMMENT '平均点击花费/成本',
    avg_cost_per_clk        STRING       COMMENT '平均点击成本(天猫专用)',
    clk_unit_amt            STRING       COMMENT '点击单价',
    jump2clk_unit_amt       STRING       COMMENT '跳转点击单价',
    
    vst_cost                STRING       COMMENT '观看成本',
    valid_vst_cpm           STRING       COMMENT '千次有效观看成本',
    valid_view_cost         STRING       COMMENT '有效播放成本(京东)',
    itm_fvt_cost            STRING       COMMENT '商品收藏成本',
    clt_itm_cost            STRING       COMMENT '宝贝收藏成本',
    clt_slr_cost            STRING       COMMENT '店铺收藏成本',
    store_follow_cost       STRING       COMMENT '店铺关注成本(京东)',
    product_follow_cost     STRING       COMMENT '商品关注成本(京东)',
    cart_itm_cost           STRING       COMMENT '加购商品成本',
    cart_cost               STRING       COMMENT '加购成本(京东)',
    clt_cart_itm_cost       STRING       COMMENT '宝贝收藏加购成本',
    all_clt_cart_itm_cost   STRING       COMMENT '总收藏加购成本',
    shop_clt_cost           STRING       COMMENT '店铺客户成本',
    cpa                     string      comment '平均订单成本',
    all_pay_ord_cost        STRING       COMMENT '总成交成本',
    laxin_cost              STRING       COMMENT '拉新成本',
    inc_fans_cost           STRING       COMMENT '新增粉丝成本',
    touch_newer_cost        STRING       COMMENT '新客触达成本',
    new_customer_cost       STRING       COMMENT '新客成本(京东)',
    zc_pay_ord_cost         STRING       COMMENT '种草引导成交成本',
    zc_crowd_retarget_cost  STRING       COMMENT '种草人群追投消耗',
    favorites_spending      STRING       COMMENT '收藏花费(拼多多)',
    avg_favorites_spending  STRING       COMMENT '平均收藏成本(拼多多)',
    focus_spending          STRING       COMMENT '关注花费(拼多多)',
    avg_focus_spending      STRING       COMMENT '平均关注成本(拼多多)',
    inquiry_spending        STRING       COMMENT '询单花费(拼多多)',
    avg_inquiry_spending    STRING       COMMENT '平均询单成本(拼多多)',
    
    -- =====================================================================
    -- 8. 渠道特有业务扩展域 (Exclusive Ext)
    -- =====================================================================
    allsite_ord_amt         STRING       COMMENT '全站交易额',
    allsite_ord_cnt         STRING       COMMENT '全站订单行',
    allsite_ord_cost        STRING       COMMENT '全站订单成本',
    allsite_fee_ratio       STRING       COMMENT '全站费比',
    allsite_roi             STRING       COMMENT '全站投产比',
    
    order_id                STRING       COMMENT '订单id',
    order_name              STRING       COMMENT '订单名称',
    schedule_id             STRING       COMMENT '排期id',
    schedule_name           STRING       COMMENT '排期名称',
    ad_slot_id              STRING       COMMENT '广告位id',
    ad_slot_name            STRING       COMMENT '广告位名称',
    exp_pv                  STRING       COMMENT '曝光数(合约)',
    exp_clk_cnt             STRING       COMMENT '曝光点击数(合约)',
    exp_clk_rate            STRING       COMMENT '曝光点击率(合约)',
    
    start_time              STRING       COMMENT '开始时间',
    expire_time             STRING       COMMENT '到期时间',
    plan_type               STRING       COMMENT '计划类型',
    market_scene            STRING       COMMENT '营销场景',
    status                  STRING       COMMENT '状态',
    item_sku                STRING       COMMENT '商品sku(直播)',
    resource_slot           STRING       COMMENT '资源位',
    
    media_type              STRING       COMMENT '媒体类型',
    placement               STRING       COMMENT '投放位置',
    one_click_cost          STRING       COMMENT '一键起量花费',
    
    clk_date                STRING       COMMENT '点击日期(京东)',
    clk_time                STRING       COMMENT '点击时间(京东)',

    uuid                    STRING       COMMENT '唯一ID/行标识(京东ly_uuid对齐至此)',
    file_id                 STRING       COMMENT '来源文件ID/系统唯一标识',
    file_name               STRING       COMMENT '来源文件名'
);
